name: Ansible Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - ansible/**
jobs:
  deploy-ansible:
    uses: camfu-co/hl_github_pipelines/.github/workflows/ansible-pipeline.yml@main
    secrets: inherit